#!/bin/bash

img_dir=/var/lib/libvirt/images
basevm=template6.7

read -p "Enter VM number: " num

if [ ${num} -le 9 ]; then
	num=0${num}
fi

if [ -z "${num}" ]; then
	echo "You Must Input a number."
	exit 65
elif [ $(echo ${num}*1 | bc) = 0 ]; then
	echo "You Must Input a number."
	exit 66
elif [ ${num} -lt 1 -o ${num} -gt 99 ]; then
	echo "The Number Which You Input Is Out of Range."
	exit 67
fi

newvm=rh6_node${num}

if [ -e ${img_dir}/${newvm}.qcow2 ]; then
	echo "${newvm}.qcow2 is exists."
	exit 68
fi

echo -en "Creating Virtual Machine disk image...\t"
qemu-img create -f qcow2 -b ${img_dir}/.${basevm}.qcow2 ${img_dir}/${newvm}.qcow2 &> /dev/null
if [ $? -eq 0 ]; then
	echo -e "\e[32;1m[OK]\e[0m"
else
	echo "created ${newvm}.qcow2 failed.."
	exit 69
fi

cat ${img_dir}/.${basevm}.xml > /tmp/myvm6.xml
sed -ri "/<name>/s/template6.7/${newvm}/" /tmp/myvm6.xml
sed -ri "/uuid/s/(<uuid>)(.*)(<\/uuid>)/\1$(uuidgen)\3/" /tmp/myvm6.xml
sed -ri "/template6.7.qcow2/s/.${basevm}/${newvm}/" /tmp/myvm6.xml
sed -ri "/11:ab/s/11:ab/11:${num}/" /tmp/myvm6.xml
sed -ri "/22:ab/s/22:ab/22:${num}/" /tmp/myvm6.xml
sed -ri "/33:ab/s/33:ab/33:${num}/" /tmp/myvm6.xml
sed -ri "/44:ab/s/44:ab/44:${num}/" /tmp/myvm6.xml

virsh define /tmp/myvm6.xml > /dev/null
if [ $? -eq 0 ]; then
	echo -e "created ${newvm}\t\t\033[32;1m[ok]\033[0m"
else 
	echo "define ${newvm} failed .."
	exit 70
fi
